#https://learn.adafruit.com/monochrome-oled-breakouts/python-wiring

- name: Install Packages
  apt:
    pkg:
      - python3-pil
      - python3-libgpiod
    state: present

- name: Install PIP3 adafruit-blinka
  ansible.builtin.pip:
    name: adafruit-blinka
    
- name: Install PIP3 adafruit-circuitpython-ssd1306
  ansible.builtin.pip:
    name: adafruit-circuitpython-ssd1306
    
    
- name: Copy /root/oledinfo.py
  copy:
    src: oledinfo.py
    dest: /root/oledinfo.py
    mode: '0754'
    backup: no
  notify: Start oledinfo service
    
- name: Copy /etc/systemd/system/oledinfo.service
  copy:
    src: oledinfo.service
    dest: /etc/systemd/system/oledinfo.service
    mode: '0644'
    backup: no
  notify: Start oledinfo service
