- name: Install Packages
  apt:
    pkg:
      - kodi
    state: latest

- name: Copy to kodi-wayland.desktop
  shell: mv /usr/share/xsessions/kodi.desktop /usr/share/wayland-sessions/kodi-wayland.desktop
  args: 
      creates: /usr/share/wayland-sessions/kodi-wayland.desktop
 
