
- name: Enable auto login
  lineinfile:
    path: /etc/gdm3/custom.conf
    regexp: '^#  AutomaticLoginEnable = true'
    line: AutomaticLoginEnable=True

- name: Enable auto login for normal_user 
  lineinfile:
    path: /etc/gdm3/custom.conf
    regexp: '^#  AutomaticLogin = user1'
    line: AutomaticLogin={{ normal_user }}
